// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UnlockTheRoom.API.Data;

#nullable disable

namespace UnlockTheRoom.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260331211629_AddRotationToGameObjects")]
    partial class AddRotationToGameObjects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UnlockTheRoom.API.Models.GameObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<int?>("LevelId")
                        .HasColumnType("integer");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<int>("Rotation")
                        .HasColumnType("integer");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.Property<float>("X")
                        .HasColumnType("real");

                    b.Property<float>("Y")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.ToTable("GameObjects");

                    b.HasDiscriminator<string>("ObjectType").HasValue("GameObject");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("UnlockTheRoom.API.Models.Level", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Columns")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsValidated")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int>("Rows")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("UnlockTheRoom.API.Models.SavedLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LevelId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("UserId");

                    b.ToTable("SavedLevels");
                });

            modelBuilder.Entity("UnlockTheRoom.API.Models.Score", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AchievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CompletionTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("LevelId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("UserId");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("UnlockTheRoom.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UnlockTheRoom.API.Models.Barrier", b =>
                {
                    b.HasBaseType("UnlockTheRoom.API.Models.GameObject");

                    b.Property<bool>("IsUnlocked")
                        .HasColumnType("boolean");

                    b.Property<string>("RequiredKeyColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("GameObjects", t =>
                        {
                            t.Property("IsUnlocked")
                                .HasColumnName("Barrier_IsUnlocked");
                        });

                    b.HasDiscriminator().HasValue("Barrier");
                });

            modelBuilder.Entity("UnlockTheRoom.API.Models.Button", b =>
                {
                    b.HasBaseType("UnlockTheRoom.API.Models.GameObject");

                    b.Property<bool>("IsActivated")
                        .HasColumnType("boolean");

                    b.Property<string>("TargetObjectType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Button");
                });

            modelBuilder.Entity("UnlockTheRoom.API.Models.ExitDoor", b =>
                {
                    b.HasBaseType("UnlockTheRoom.API.Models.GameObject");

                    b.Property<bool>("IsUnlocked")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue("ExitDoor");
                });

            modelBuilder.Entity("UnlockTheRoom.API.Models.Hazard", b =>
                {
                    b.HasBaseType("UnlockTheRoom.API.Models.GameObject");

                    b.Property<string>("HazardType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Hazard");
                });

            modelBuilder.Entity("UnlockTheRoom.API.Models.Key", b =>
                {
                    b.HasBaseType("UnlockTheRoom.API.Models.GameObject");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCollected")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue("Key");
                });

            modelBuilder.Entity("UnlockTheRoom.API.Models.GameObject", b =>
                {
                    b.HasOne("UnlockTheRoom.API.Models.Level", "Level")
                        .WithMany("GameObjects")
                        .HasForeignKey("LevelId");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("UnlockTheRoom.API.Models.SavedLevel", b =>
                {
                    b.HasOne("UnlockTheRoom.API.Models.Level", "Level")
                        .WithMany("SavedLevels")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UnlockTheRoom.API.Models.User", "User")
                        .WithMany("SavedLevels")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UnlockTheRoom.API.Models.Score", b =>
                {
                    b.HasOne("UnlockTheRoom.API.Models.Level", "Level")
                        .WithMany("Scores")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UnlockTheRoom.API.Models.User", "User")
                        .WithMany("Scores")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UnlockTheRoom.API.Models.Level", b =>
                {
                    b.Navigation("GameObjects");

                    b.Navigation("SavedLevels");

                    b.Navigation("Scores");
                });

            modelBuilder.Entity("UnlockTheRoom.API.Models.User", b =>
                {
                    b.Navigation("SavedLevels");

                    b.Navigation("Scores");
                });
#pragma warning restore 612, 618
        }
    }
}
